package com.prismamp.consultas.api.model;

public enum Operacion {
	CONSULTA_DEUDAS,
	ULTIMOS_PAGOS,
	CONSULTA_DISPONIBLE,
	CONSULTA_FACTURAS,
	CONSULTA_DEUDAS_CON_CB,
	CONSULTA_COMPANIA,
	CONSULTA_BANCO,
	ULTIMAS_TRANSFERENCIAS,
	ULTIMOS_MOVIMIENTOS
}